#!/bin/bash
set -e
. /usr/share/debconf/confmodule

# Habilitando o serviço do maratona-firewall para ser executado no boot do
# sistema.
systemctl enable maratona-firewall.service

priority=medium

db_input high maratona-firewall/bocaip || true
db_go || true

db_get maratona-firewall/bocaip || true
config-ip-boca "$RET" -f

# Supondo que foi tudo bonito -- Fazer script de verificação segura.
. /etc/bocaip

# Reset no ufw - apaga tudo e volta para o padrao
ufw -f reset

# With no configured BOCAIP we leave with no configuration but we may exit
# safely
if [[ "x$BOCAIP" == "x" ]]; then
	printf "Ops. IP do servidor não configurado.\n"
	printf "Informe o IP do servidor BOCA com o comando:\n"
	printf "    sudo dpkg-reconfigure maratona-firewall\n"
  exit 0
fi

# Por padrao, o firewall vem desligado
ufw enable

# Atribuindo o comportamento padrao
# Deve servir tanto para os pacotes ipv4 como o ipv6 que nao se encaixam nas
# regras descritas a seguir.
ufw default deny incoming
ufw default deny outgoing
ufw default deny routed

# Permitindo pacotes na interface loopback - Valido para IPv4 e v6.
ufw allow in on lo
ufw allow out on lo

# Para o $BOCAIP vale tudo
ufw allow out proto udp to $BOCAIP
ufw allow out proto tcp to $BOCAIP

# Rejeitando os pacotes udp e tcp para qualquer ip
ufw reject out proto udp to any
ufw reject out proto tcp to any

# Para o firewall só fazer efeito no reboot.
ufw disable
