#!/bin/bash
set -e
. /usr/share/debconf/confmodule

# Habilitando o serviço do maratona-firewall para ser executado no boot do
# sistema.
systemctl enable maratona-firewall.service

priority=medium

db_input high maratona-firewall/bocaip || true
db_go || true

db_get maratona-firewall/bocaip || true
config-ip-boca "$RET" -f
